name: impactlyflutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  auto_size_text: null
  cupertino_icons: ^1.0.8
  dartz: null
  dotted_border: 2.1.0
  encrypt: ^5.0.3
  file_picker: ^10.2.0
<<<<<<< HEAD
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.0
=======
>>>>>>> 825b2bb55dfeb431a16107c04ddf047000640836
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.14.4
<<<<<<< HEAD
  flutter_local_notifications: ^19.4.1
=======
>>>>>>> 825b2bb55dfeb431a16107c04ddf047000640836
  flutter_localizations:
    sdk: flutter
  flutter_rating: null
  flutter_rating_bar: null
  flutter_screenutil: ^5.9.3
  flutter_svg: null
  gap: null
  http: null
  image_picker: ^1.1.2
  intl: null
<<<<<<< HEAD
  introduction_screen: ^4.0.0
=======
>>>>>>> 825b2bb55dfeb431a16107c04ddf047000640836
  loading_animation_widget: ^1.3.0
  logger: ^2.5.0
  material_symbols_icons: ^4.2805.1
  mobile_scanner: ^7.0.1
  multi_select_flutter: ^4.1.3
  page_transition: ^2.1.0
  path_provider: ^2.1.5
  persistent_bottom_nav_bar: ^6.2.1
  pretty_qr_code: ^3.5.0
  provider: ^6.1.1
  rename: ^3.1.0
  shared_preferences: null
<<<<<<< HEAD
  skeletonizer: null
=======
  skeletonizer: 
>>>>>>> 825b2bb55dfeb431a16107c04ddf047000640836
  top_snackbar_flutter: ^3.1.0
  video_player: ^2.10.0
  video_thumbnail: ^0.5.6

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
<<<<<<< HEAD
  generate: true
=======
>>>>>>> 825b2bb55dfeb431a16107c04ddf047000640836

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/PNG/
    - assets/SVG/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter_18pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_18pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter_18pt-Black.ttf
          weight: 900
